device: cuda:0

log_dir: output
data_dir: event_data
metadata_dir: metadata
cache_dir: cached_dataset

model: CNN_GRU
lr: 0.0005
num_epochs: 800
batch_size: 16
spatial_factor: 0.125
temporal_subsample_factor: 0.2
val_interval: 10
save_k_best: 2
pixel_tolerances: [5,10,15]

sensor_width: 640
sensor_height: 480
train_length: 30
train_stride: 15
val_length: 90
val_stride: 90
test_length: 90
test_stride: 90
n_time_bins: 4
voxel_grid_ch_normaization: false